"use client";

import { useCallback, useEffect, useMemo, useRef, useState, type KeyboardEvent } from "react";
import type { Data, Layout } from "plotly.js";
import Chart from "@/components/charts/Chart";
import { useEstimate } from "@/lib/api";
import { clock, propLabel } from "@/lib/format";
import { baseLayout } from "@/lib/plotTheme";
import { useCockpit, type ChatMessage } from "@/lib/store";
import { Citations } from "@/components/ui/primitives";
import { IconAlert, IconMinimise, IconMic, IconSend, IconSpark, IconStop, IconTrash } from "@/components/ui/icons";
import Markdown from "./Markdown";
import SourcePreview from "./SourcePreview";
import { useCopilotChat, usePageContext } from "./useCopilotChat";
import { useLiveVoice, type LiveVoice } from "./useLiveVoice";

const STARTERS = [
  "Is the soft sensor trustworthy right now?",
  "Why did the estimate move in the last hour?",
  "Can we raise the LCO cut point now?",
  "Summarise model agreement at this minute.",
];

function InlineChart({ figure }: { figure: unknown }) {
  const theme = useCockpit((s) => s.theme);
  const fig = (figure ?? {}) as { data?: Data[]; layout?: Partial<Layout> };
  const layout = useMemo(
    () =>
      baseLayout(theme, {
        ...(fig.layout ?? {}),
        paper_bgcolor: "rgba(0,0,0,0)",
        plot_bgcolor: "rgba(0,0,0,0)",
        margin: { l: 44, r: 10, t: fig.layout?.title ? 30 : 10, b: 32 },
        height: undefined,
        width: undefined,
      }),
    [fig.layout, theme],
  );
  if (!Array.isArray(fig.data)) return null;
  return (
    <div className="inline-chart">
      <Chart data={fig.data} layout={layout} height={220} ariaLabel="Chart generated by the copilot" />
    </div>
  );
}

function Message({ m, onSuggest }: { m: ChatMessage; onSuggest: (s: string) => void }) {
  if (m.role === "user") {
    return (
      <div className="msg user">
        <div className="bubble">{m.content}</div>
        {m.voice ? <span className="subtle" style={{ fontSize: 10.5 }}>voice</span> : null}
      </div>
    );
  }
  return (
    <div className="msg assistant" aria-live={m.streaming ? "polite" : undefined}>
      {m.streaming && m.status ? (
        <div className="status-line" role="status">
          <span className="spinner" aria-hidden />
          <span className="txt">{m.status}</span>
        </div>
      ) : null}
      {m.content ? (
        <div className="bubble">
          <Markdown>{m.content}</Markdown>
        </div>
      ) : null}
      {(m.charts ?? []).map((f, i) => (
        <InlineChart key={i} figure={f} />
      ))}
      <Citations items={m.citations} />
      {m.error ? (
        <div className="banner error" role="alert" style={{ padding: "8px 12px" }}>
          <IconAlert />
          <span>{m.error}</span>
        </div>
      ) : null}
      {!m.streaming && (m.content || m.voice) ? (
        <div className="row" style={{ gap: 6 }}>
          <span className="generated-label">Generated{m.voice ? " · voice" : ""}</span>
          {m.tools?.length ? <span className="subtle" style={{ fontSize: 10.5 }}>tools: {[...new Set(m.tools)].join(", ")}</span> : null}
        </div>
      ) : null}
      {m.suggestions?.length && !m.streaming ? (
        <div className="sugg">
          {m.suggestions.map((s) => (
            <button key={s} type="button" onClick={() => onSuggest(s)}>
              {s}
            </button>
          ))}
        </div>
      ) : null}
    </div>
  );
}

function Meter({ level }: { level: number }) {
  const bars = 18;
  return (
    <div className="meter" aria-hidden>
      {Array.from({ length: bars }, (_, i) => {
        const shape = Math.sin((i / (bars - 1)) * Math.PI);
        const h = 3 + level * 24 * (0.35 + 0.65 * shape) * (0.75 + 0.25 * Math.sin(i * 1.7));
        return <span key={i} style={{ height: `${Math.max(3, h)}px` }} />;
      })}
    </div>
  );
}

const VOICE_LABEL: Record<string, string> = {
  idle: "Voice off",
  connecting: "Connecting…",
  ready: "Ready",
  listening: "Listening…",
  speaking: "Gemini is speaking",
  error: "Voice unavailable",
};

function VoiceBar({ v }: { v: LiveVoice }) {
  const live = v.state === "listening";
  const onDown = () => {
    if (v.mode === "ptt") void v.startTalking();
  };
  const onUp = () => {
    if (v.mode === "ptt") v.stopTalking();
  };
  const onClick = () => {
    if (v.mode === "handsfree") {
      if (live) v.stopTalking();
      else void v.startTalking();
    }
  };
  const onKeyDown = (e: KeyboardEvent<HTMLButtonElement>) => {
    if (v.mode === "ptt" && (e.key === " " || e.key === "Enter") && !e.repeat) {
      e.preventDefault();
      void v.startTalking();
    }
  };
  const onKeyUp = (e: KeyboardEvent<HTMLButtonElement>) => {
    if (v.mode === "ptt" && (e.key === " " || e.key === "Enter")) {
      e.preventDefault();
      v.stopTalking();
    }
  };
  return (
    <div className="voice-bar">
      <div className="row between" style={{ width: "100%" }}>
        <div className="seg" role="group" aria-label="Voice mode">
          <button
            type="button"
            aria-pressed={v.mode === "ptt"}
            onClick={() => {
              v.stopTalking();
              v.setMode("ptt");
            }}
          >
            Push-to-talk
          </button>
          <button type="button" aria-pressed={v.mode === "handsfree"} onClick={() => v.setMode("handsfree")}>
            Hands-free
          </button>
        </div>
        <button type="button" className="btn sm ghost" onClick={v.disconnect} disabled={v.state === "idle"}>
          <IconStop /> End voice
        </button>
      </div>
      <div className="voice">
        <button
          type="button"
          className={`mic ${live ? "live" : ""}`}
          aria-label={v.mode === "ptt" ? "Hold to talk" : live ? "Stop listening" : "Start hands-free listening"}
          aria-pressed={live}
          onPointerDown={onDown}
          onPointerUp={onUp}
          onPointerLeave={onUp}
          onClick={onClick}
          onKeyDown={onKeyDown}
          onKeyUp={onKeyUp}
          id="voice-mic"
        >
          <span className="mic-ring" style={{ opacity: live ? 0.25 + v.level * 0.75 : 0 }} />
          <IconMic />
        </button>
        <Meter level={v.level} />
        <div className="voice-state" role="status" aria-live="polite">
          {VOICE_LABEL[v.state]}
        </div>
        <div className="voice-sub">
          {v.mode === "ptt" ? "Hold the mic (or Space) while speaking" : "Speak naturally — Gemini detects turns"}
          {v.model ? ` · ${v.model}` : " · Gemini Live"}
        </div>
      </div>
      {v.error ? (
        <div className="banner error" role="alert" style={{ padding: "8px 12px", width: "100%" }}>
          <IconAlert />
          <span>{v.error}</span>
        </div>
      ) : null}
    </div>
  );
}

function Panel({ voice, onClose }: { voice: LiveVoice; onClose: () => void }) {
  const messages = useCockpit((s) => s.messages);
  const setMessages = useCockpit((s) => s.setMessages);
  const expanded = useCockpit((s) => s.copilotExpanded);
  const pending = useCockpit((s) => s.pendingPrompt);
  const clearPending = useCockpit((s) => s.clearPending);
  const tab = useCockpit((s) => s.copilotTab);
  const source = useCockpit((s) => s.sourcePreview);
  const setTab = useCockpit((s) => s.setCopilotTab);
  const ctx = usePageContext();
  const { send, stop, busy } = useCopilotChat();
  const [draft, setDraft] = useState("");
  const bodyRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    bodyRef.current?.scrollTo({ top: bodyRef.current.scrollHeight });
  }, [messages]);

  useEffect(() => {
    if (tab === "text") inputRef.current?.focus();
  }, [tab]);

  useEffect(() => {
    if (pending) {
      clearPending();
      void send(pending);
    }
  }, [pending, clearPending, send]);

  const submit = () => {
    if (!draft.trim()) return;
    void send(draft);
    setDraft("");
  };

  return (
    <div
      className={`drawer ${expanded ? "expanded" : ""}`}
      role="dialog"
      aria-label="Gemini copilot"
      aria-modal="false"
      id="copilot-panel"
    >
      <div className="drawer-inner">
        <div className="drawer-h">
          <IconSpark width={20} height={20} style={{ color: "var(--accent)" }} />
          <h2>Gemini</h2>
          <button
            type="button"
            className="btn icon ghost"
            onClick={() => setMessages(() => [])}
            aria-label="Clear conversation"
            title="Clear conversation"
            disabled={busy || !messages.length}
          >
            <IconTrash />
          </button>
          <button
            type="button"
            className="btn icon ghost"
            onClick={() => useCockpit.setState({ copilotExpanded: !expanded })}
            aria-label={expanded ? "Shrink panel" : "Expand panel"}
            title={expanded ? "Shrink" : "Expand"}
          >
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden>
              {expanded ? <path d="M9 4v5H4M15 20v-5h5M4 9l6-6M20 15l-6 6" /> : <path d="M4 9V4h5M20 15v5h-5M4 4l6 6M20 20l-6-6" />}
            </svg>
          </button>
          <button type="button" className="btn icon ghost" onClick={onClose} aria-label="Minimise Gemini (Esc)" title="Minimise (Esc)">
            <IconMinimise />
          </button>
        </div>
        <div className="drawer-ctx" aria-label="Context sent with each question">
          <span>Context:</span>
          <span className="mono">{ctx.page}</span>·<span className="mono">{ctx.run_id ?? "no run"}</span>·
          <span>{propLabel(ctx.property)}</span>·<span className="mono">t {ctx.time_min ?? "—"} ({clock(ctx.time_min)})</span>
        </div>
        <div className="drawer-body" ref={bodyRef}>
          {source ? (
            <SourcePreview c={source} />
          ) : !messages.length ? (
            <div className="stack" style={{ gap: 12 }}>
              <p className="muted" style={{ margin: 0 }}>
                Ask about estimates, the spread gate, recommendations, models or procedures. Answers use read-only
                tools over simulated data and cite documents as <span className="mono">[DOC-ID rN §x.y]</span>.
              </p>
              <div className="sugg">
                {STARTERS.map((s) => (
                  <button key={s} type="button" onClick={() => void send(s)}>
                    {s}
                  </button>
                ))}
              </div>
            </div>
          ) : (
            messages.map((m) => <Message key={m.id} m={m} onSuggest={(s) => void send(s)} />)
          )}
        </div>
        <div className="drawer-foot">
          {tab === "voice" ? <VoiceBar v={voice} /> : null}
          <div className="composer">
            <label htmlFor="copilot-input" className="sr-only">
              Message Gemini
            </label>
            <textarea
              id="copilot-input"
              ref={inputRef}
              rows={1}
              placeholder="Ask about the unit…"
              value={draft}
              onChange={(e) => setDraft(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  submit();
                }
              }}
            />
            <button
              type="button"
              className={`btn icon ${tab === "voice" ? "primary" : ""}`}
              aria-pressed={tab === "voice"}
              aria-label={tab === "voice" ? "Hide voice controls" : "Talk to Gemini Live"}
              title="Gemini Live voice"
              onClick={() => setTab(tab === "voice" ? "text" : "voice")}
            >
              <IconMic />
            </button>
            {busy ? (
              <button type="button" className="btn icon" onClick={stop} aria-label="Stop generating">
                <IconStop />
              </button>
            ) : (
              <button
                type="button"
                className="btn icon primary"
                onClick={submit}
                disabled={!draft.trim()}
                aria-label="Send"
              >
                <IconSend />
              </button>
            )}
          </div>
          <div className="subtle" style={{ fontSize: 10.5 }}>
            Advisory only · read-only tools · nothing is written to any control system.
          </div>
        </div>
      </div>
    </div>
  );
}

/** Floating launcher (bottom-right, every page) + overlay panel. Voice session survives collapse. */
export default function CopilotLauncher() {
  const open = useCockpit((s) => s.copilotOpen);
  const setOpen = useCockpit((s) => s.setCopilotOpen);
  const voiceActive = useCockpit((s) => s.voiceActive);
  const runId = useCockpit((s) => s.runId);
  const property = useCockpit((s) => s.property);
  const timeMin = useCockpit((s) => s.timeMin);
  const est = useEstimate(runId, property, timeMin);
  const withheld = est.data?.gate?.status === "WITHHELD";
  const voice = useLiveVoice();
  const launcherRef = useRef<HTMLButtonElement>(null);

  const close = useCallback(() => {
    setOpen(false);
    launcherRef.current?.focus();
  }, [setOpen]);

  useEffect(() => {
    const onKey = (e: globalThis.KeyboardEvent) => {
      const target = e.target as HTMLElement | null;
      const typing = !!target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA" || target.isContentEditable);
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") {
        e.preventDefault();
        setOpen(!useCockpit.getState().copilotOpen);
      } else if (e.key === "/" && !typing && !e.metaKey && !e.ctrlKey) {
        e.preventDefault();
        setOpen(true);
      } else if (e.key === "Escape" && useCockpit.getState().copilotOpen) {
        const st = useCockpit.getState();
        if (st.sourcePreview) st.closeSource();
        else close();
      }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [close, setOpen]);

  return (
    <>
      {open ? <Panel voice={voice} onClose={close} /> : null}
      <button
        ref={launcherRef}
        type="button"
        className="launcher"
        onClick={() => setOpen(!open)}
        aria-expanded={open}
        aria-controls="copilot-panel"
        aria-label={`${open ? "Minimise" : "Ask"} Gemini${withheld ? " — gate withheld" : ""}${voiceActive ? " — voice live" : ""}`}
        id="copilot-launcher"
      >
        <IconSpark />
        {withheld ? <span className="ldot withheld" title="Gate WITHHELD" /> : null}
        <span>{open ? "Minimise" : "Ask Gemini"}</span>
        {voiceActive ? <span className="live-ind">LIVE</span> : <kbd>⌘K</kbd>}
      </button>
    </>
  );
}
