"""Copilot package for FCC Soft-Sensor Decision Cockpit."""
from .adk_agent import (
    ADK_CANONICAL_TOOLS,
    ALL_TOOLS,
    AdkCompatibleAgent,
    Agent,
    HAS_GOOGLE_ADK,
    create_fcc_agent,
    draft_handover,
    explain_estimate,
    find_similar_events,
    get_distribution,
    get_document_section,
    get_gate_status,
    get_lab_history,
    get_model_metrics,
    get_recommendations,
    get_run_snapshot,
    make_chart,
    query_timeseries,
    root_agent,
    run_sql_readonly,
    run_whatif,
    search_documents,
)
from .chat import chat_stream, system_instruction

__all__ = [
    "ADK_CANONICAL_TOOLS",
    "ALL_TOOLS",
    "AdkCompatibleAgent",
    "Agent",
    "HAS_GOOGLE_ADK",
    "chat_stream",
    "create_fcc_agent",
    "draft_handover",
    "explain_estimate",
    "find_similar_events",
    "get_distribution",
    "get_document_section",
    "get_gate_status",
    "get_lab_history",
    "get_model_metrics",
    "get_recommendations",
    "get_run_snapshot",
    "make_chart",
    "query_timeseries",
    "root_agent",
    "run_sql_readonly",
    "run_whatif",
    "search_documents",
    "system_instruction",
]
