import json
import logging
import numpy as np
import pandas as pd
import scipy.stats as stats
import time

from app.state import get_state
from app.engines.regime import regime_at
from app.engines.surrogates import expected_series, predict, INPUTS, OUTPUTS, _load_surrogates

logger = logging.getLogger(__name__)

UNIT_MVS = {
    "unit_4_fractionator": ["SP_LCO_T98", "SP_HN_T98", "MV_PA1", "MV_PA2", "MV_PA3", "MV_PA4"],
    "unit_1_furnace": ["SP_T_preheat_F"],
    "unit_2_riser": ["SP_T_riser_ROT_F"],
    "unit_3_regenerator": ["Fair", "SP_T_reg_F"],
    "unit_5_condenser": ["MV_reflux_ratio", "SP_T_overhead", "MV_cw_flow"],
    "unit_6_stabiliser": ["MV_reflux_ratio", "SP_T_overhead", "MV_cw_flow"]
}

def get_limits(s):
    return s.get("iow", {})

def recipe_for(run_id: str, time_min: int, unit_id: str) -> dict:
    st = get_state()
    df = st.catalog.load(run_id)
    if df.empty:
        return {"gate": "WITHHELD", "gate_reason": "insufficient_data"}
        
    t_min_arr = df["time_min"].values
    idx = np.searchsorted(t_min_arr, time_min)
    if idx >= len(t_min_arr) or t_min_arr[idx] > time_min:
        idx = max(0, idx - 1)
        
    row = df.iloc[idx].to_dict()
    
    reg_info = regime_at(run_id, time_min)
    regime_id = reg_info.get("regime_id", "R3")
    novelty = reg_info.get("novelty", 0.0)
    
    if novelty > 0.7:
        return {"gate": "WITHHELD", "gate_reason": "novelty"}
        
    # get MV subset for unit
    mvs_to_search = [m for m in UNIT_MVS.get(unit_id, []) if m in INPUTS and m in row]
    if "SP_T_overhead" not in mvs_to_search and "MV_cw_flow" in UNIT_MVS.get(unit_id, []) and "MV_cw_flow" in INPUTS:
        mvs_to_search.append("MV_cw_flow")
        
    if len(mvs_to_search) < 2:
        return {"gate": "WITHHELD", "gate_reason": "infeasible"}
        
    limits = get_limits(st.s)
    
    # bounds logic
    bounds = {}
    for mv in mvs_to_search:
        cur = row[mv]
        lim_lo, lim_hi = limits.get(mv, [cur - 10, cur + 10])
        
        if "ROT" in mv:
            step = 5.0
        elif "SP_" in mv:
            step = 10.0
        elif "PA" in mv or "Fair" in mv or "MV_" in mv:
            step = 5.0
        else:
            step = 5.0
            
        lo = max(lim_lo, cur - step)
        hi = min(lim_hi, cur + step)
        if lo > hi:
            lo, hi = hi, lo
        bounds[mv] = (lo, hi, cur)
        
    # random search
    best_obj = -np.inf
    best_moves = None
    best_res = None
    
    start_t = time.time()
    
    # Evaluate current
    base_res = _eval_moves(regime_id, row, {}, run_id, time_min)
    base_obj = base_res["objective"]
    
    for _ in range(8):
        if time.time() - start_t > 0.18:
            break
        
        # coordinate descent / random sample
        for _s in range(10): # 10 samples per restart
            moves = {}
            for mv, (lo, hi, cur) in bounds.items():
                moves[mv] = np.random.uniform(lo, hi)
                
            res = _eval_moves(regime_id, row, moves, run_id, time_min)
            if res["feasible"] and res["objective"] > best_obj:
                best_obj = res["objective"]
                best_moves = moves
                best_res = res
                
    if best_moves is None or best_obj <= base_obj + 1e-4:
        return {"gate": "WITHHELD", "gate_reason": "infeasible"}
        
    moves_list = []
    for mv, val in best_moves.items():
        cur = bounds[mv][2]
        lims = limits.get(mv, [0, 0])
        moves_list.append({
            "sp_tag": mv, "label": mv, "current": round(cur, 2),
            "recommended": round(val, 2), "delta": round(val - cur, 2),
            "unit": "°F" if "SP" in mv else "%",
            "limit_lo": lims[0], "limit_hi": lims[1]
        })
        
    if len(moves_list) < 2:
        return {"gate": "WITHHELD", "gate_reason": "infeasible"}
        
    recipe_id = f"rcp_{run_id}_{unit_id}_{time_min:06d}"
    
    return {
        "recipe_id": recipe_id,
        "run_id": run_id,
        "time_min": time_min,
        "unit_id": unit_id,
        "regime_id": regime_id,
        "gate": "ISSUED",
        "gate_reason": None,
        "moves": moves_list,
        "d_yield_pct_feed": best_res["d_yield"],
        "d_fuel_lb_s": round(best_res["d_fuel"], 2),
        "d_power_MW": round(best_res["d_power"], 2),
        "d_coke_pct": round(best_res["d_coke"], 2),
        "p_on_spec": best_res["p_on_spec"],
        "objective_before": round(base_obj, 2),
        "objective_after": round(best_obj, 2),
        "predicted": best_res["predicted"],
        "citations": st.citations_for("LCO_T98_F", "adjust"),
        "explanation": "Recipe generated by random restart coordinate search."
    }

def whatif(run_id: str, time_min: int, unit_id: str, moves: dict) -> dict:
    st = get_state()
    df = st.catalog.load(run_id)
    if df.empty:
        return {}
    t_min_arr = df["time_min"].values
    idx = np.searchsorted(t_min_arr, time_min)
    if idx >= len(t_min_arr) or t_min_arr[idx] > time_min:
        idx = max(0, idx - 1)
    row = df.iloc[idx].to_dict()
    
    reg_info = regime_at(run_id, time_min)
    regime_id = reg_info.get("regime_id", "R3")
    
    res = _eval_moves(regime_id, row, moves, run_id, time_min)
    return {
        "predicted": res["predicted"],
        "d_yield_pct_feed": res["d_yield"],
        "p_on_spec": res["p_on_spec"],
        "within_limits": res["feasible"]
    }

def _eval_moves(regime_id, row, moves, run_id, time_min):
    st = get_state()
    base_x = {k: row.get(k, 0.0) for k in INPUTS}
    new_x = dict(base_x)
    new_x.update(moves)
    
    base_y = predict(regime_id, base_x)
    new_y = predict(regime_id, new_x)
    
    feed = row.get("feed_flow_lb_s", 100.0)
    if feed < 1e-3: feed = 100.0
    
    # get sd from st.run or fallback
    v = st.run(run_id)
    sd = {"LCO_T98_F": 2.0, "HN_T98_F": 2.0}
    if v:
        arrs, _ = v
        t_est = arrs["time_min"]
        idx = np.searchsorted(t_est, time_min)
        if idx < len(t_est) and t_est[idx] == time_min:
            sd["LCO_T98_F"] = arrs.get("LCO_T98_F|sd", [2.0])[idx]
            sd["HN_T98_F"] = arrs.get("HN_T98_F|sd", [2.0])[idx]
            
    p_on_spec = {}
    feasible = True
    specs = st.s["specs"]
    
    for prop in ["LCO_T98_F", "HN_T98_F"]:
        if prop in new_y:
            mu = new_y[prop]
            sigma = max(0.1, sd[prop])
            spec = specs.get(prop, {}).get("max", 999.0)
            z = (spec - mu) / sigma
            p = stats.norm.cdf(z)
            p_on_spec[prop.split("_")[0]] = round(float(p), 2)
            if p < 0.95:
                feasible = False
                
    rcp_cfg = st.s.get("recipe", {})
    
    def yield_pct(y_dict, out):
        return (y_dict.get(out, 0) / (feed * 60)) * 100
        
    y_LCO = yield_pct(new_y, "prod_LCO")
    y_HN = yield_pct(new_y, "prod_HN")
    y_LPG = yield_pct(new_y, "prod_LPG")
    
    fuel = new_y.get("F5_fuel", 0)
    power = new_y.get("power_CAB", 0) + new_y.get("power_WGC", 0)
    coke = yield_pct(new_y, "F_coke")
    
    obj = (
        rcp_cfg.get("w_LCO", 1.0) * y_LCO +
        rcp_cfg.get("w_HN", 0.8) * y_HN +
        rcp_cfg.get("w_LPG", 0.4) * y_LPG -
        rcp_cfg.get("p_F5_fuel", 0.1) * fuel -
        rcp_cfg.get("p_power", 0.1) * (power / 100) -
        rcp_cfg.get("p_coke", 0.1) * coke
    )
    
    d_yield = {
        "LCO": round(yield_pct(new_y, "prod_LCO") - yield_pct(base_y, "prod_LCO"), 2),
        "HN": round(yield_pct(new_y, "prod_HN") - yield_pct(base_y, "prod_HN"), 2),
        "LN": round(yield_pct(new_y, "prod_LN") - yield_pct(base_y, "prod_LN"), 2),
        "LPG": round(yield_pct(new_y, "prod_LPG") - yield_pct(base_y, "prod_LPG"), 2)
    }
    
    return {
        "objective": obj,
        "feasible": feasible,
        "p_on_spec": p_on_spec,
        "d_yield": d_yield,
        "d_fuel": new_y.get("F5_fuel", 0) - base_y.get("F5_fuel", 0),
        "d_power": (new_y.get("power_CAB", 0) + new_y.get("power_WGC", 0)) - (base_y.get("power_CAB", 0) + base_y.get("power_WGC", 0)),
        "d_coke": yield_pct(new_y, "F_coke") - yield_pct(base_y, "F_coke"),
        "predicted": {k: round(v, 1) for k, v in new_y.items() if k in ["LCO_T98_F", "HN_T98_F", "prod_LCO"]}
    }
